spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456

  liquibase:
    change-log: classpath:liquibase/changelog.yml

server:
  error:
    include-stacktrace: on_param